# Generated by Django 3.1.4 on 2021-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
                ('blog_text', models.CharField(max_length=300)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
