# Generated by Django 3.1.4 on 2021-01-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField()),
                ('post_text', models.CharField(max_length=3000)),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
